#!/bin/bash

error(){
    message="$1"
    if test -z "$message"; then
        echo "!!! เกิดข้อผิดพลาด"
    else
        echo "!!! $message"
    fi
    exit
}

end(){
    echo "$>> $1เรียบร้อย"
}

newuser(){
    botname="$1"
    (test -z "$botname") && error "โปรดระบุชื่อบอต"
    name=.$RANDOM
    cp templates/user-config.py tmp/$name
    nano tmp/$name
    if ! diff tmp/$name templates/user-config.py; then
        mkdir -p bots/$botname
        mv tmp/$name bots/$botname/user-config.py
    fi
}

new(){
    command="$1"
    shift
    case "$command" in
    "script")
        echo "NotImplemented"
        ;;
    "user")
        newuser "$@"
        ;;
    *)
        error "เรียกใช้พารามิเตอร์ไม่ถูกต้อง"
        ;;
    esac
}

testscript(){
    cd bots
    for i in *; do
        python ../scripts/login.py -bot:$i
    done
}

run(){
    script="$1"
    shift
    python ./scripts/"$script" "$@" -bot:Nullzerobot
}

remove(){
    command="$1"
    shift
    case "$command" in
    "lock")
        rm -v tmp/*.lock
        echo "$>> ปลดล็อกแล้ว"
        ;;
    "pyc")
        find . -type f | grep -P "\.pyc$" | xargs rm
        find . -type f | grep -P "\.pyo$" | xargs rm
        echo "$>> ลบไฟล์ pyc เรียบร้อย"
        ;;
    "git")
        git ls-files -z --deleted | while read -r -d '' file; do
            git rm "$file"
        done
        echo "$>> ลบไฟล์ git เรียบร้อย"
        ;;
    "delay")
        find ./bots -type f | grep "throttle.ctrl" | xargs rm
        echo "$>> ล้างไฟล์หน่วงแล้ว"
        ;;
    "log")
        echo "NotImplemented"
        ;;
    *)
        error "เรียกใช้พารามิเตอร์ไม่ถูกต้อง"
        ;;
    esac
}

cd "$(dirname $0)"
mode="$1"
shift
case "$mode" in
"r")
    run "$@"
    ;;
"rm")
    remove "$@"
    ;;
"new")
    new "$@"
    ;;
"test")
    testscript
    ;;
"setup")
    cp templates/bash_completion ~/.wprobotrc
    ;;
*)
    error "เรียกใช้พารามิเตอร์ไม่ถูกต้อง"
    ;;
esac
