#!/bin/bash

current_dir="$(dirname $0)"

error(){
    message="$1"
    if test -z "$message"; then
        echo "!!! เกิดข้อผิดพลาด"
    else
        echo "!!! $message"
    fi
    exit
}

end(){
    echo "$>> $1เรียบร้อย"
}

createuser(){
    botname="$1"
    (test -z "$botname") && error "โปรดระบุชื่อบอต"
    cd pywikipedia
    python generate_user_files.py
    cd ../bots
    mkdir "$botname"
    cd "$botname"
    ln -s ../../pywikipedia/families
    ln -s ../../pywikipedia/userinterfaces
    mv ../../pywikipedia/user-config.py .
    python ../../pywikipedia/login.py
}

testscript(){
    cd bots
    for i in *; do
        cd $i
        python ./../../pywikipedia/replace.py -page:User:"$i"/ts -regex "(?s)^(.*)$" "$RANDOM" -summary:ทดสอบ -always
        cd ..
    done
}

remove(){
    command="$1"
    shift
    case "$command" in
    "lock")
        rm "${current_dir}"/tmp/*.lock
        echo "$>> ปลดล็อกแล้ว"
        ;;
    "pyc")
        find "${current_dir}" -type f | grep -P "\.pyc$" | xargs rm
        find "${current_dir}" -type f | grep -P "\.pyo$" | xargs rm
        echo "$>> ลบไฟล์ pyc เรียบร้อย"
        ;;
    "git")
        git ls-files -z --deleted | while read -r -d '' file; do
            git rm "$file"
        done
        echo "$>> ลบไฟล์ git เรียบร้อย"
        ;;
    "delay")
        find ./bots -type f | grep "throttle.ctrl" | xargs rm
        echo "$>> ล้างไฟล์หน่วงแล้ว"
        ;;
    *)
        error "เรียกใช้พารามิเตอร์ไม่ถูกต้อง"
        ;;
    esac
}

cd "$current_dir"
mode="$1"
shift
case "$mode" in
"rm")
    remove "$@"
    ;;
*)
    error "เรียกใช้พารามิเตอร์ไม่ถูกต้อง"
    ;;
esac
