#!/bin/bash

function submitB(){
    jsub $2 -once -j y -o /dev/null ~/wprobot/scripts/$1 -bot:Nullzerobot
}

function autoCategory(){
    submitB autoCategory.py "-mem 512m"
}

function submit(){
    submitB $1 "$2"
}

function wlog(){
    tail -F -n 100 ~/wprobot/bots/Nullzerobot/logs/$1
}

function _runwp(){
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    opts="r rm new test setup"

    if [[ ${COMP_CWORD} -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
        return 0
    fi

    case "$prev" in
    "r")
        local files=$(for x in scripts/* ; do \
                                echo ${x##*/} ; \
                                done)
        COMPREPLY=( $(compgen -W "${files}" -- ${cur}) )
        ;;
    "rm")
        local optsrm="git lock pyc delay log"
        COMPREPLY=( $(compgen -W "${optsrm}" -- ${cur}) )
        ;;
    "new")
        local optsrm="script user"
        COMPREPLY=( $(compgen -W "${optsrm}" -- ${cur}) )
        ;;
    esac
} && complete -F _runwp runwp

function _sscript(){
    local cur
    cur="${COMP_WORDS[COMP_CWORD]}"
    local files=$(for x in ~/wprobot/scripts/* ; do \
                                echo ${x##*/} ; \
                                done)
    COMPREPLY=( $(compgen -W "${files}" -- ${cur}) )
} && complete -F _sscript submit

function _wlog(){
    local cur
    cur="${COMP_WORDS[COMP_CWORD]}"
    local files=$(for x in ~/wprobot/bots/Nullzerobot/logs/* ; do \
                                echo ${x##*/} ; \
                                done)
    COMPREPLY=( $(compgen -W "${files}" -- ${cur}) )
} && complete -F _wlog wlog

#"open")
        #local files=$(for x in * ; do \
                                #echo ${x##*/} ; \
                                #done)
        #_filedir
        #;;
